// @file PartManager_KicadLibTable.h
// @brief Merging PartManager's libraries into a KiCad `sym-lib-table` / `fp-lib-table` (§5a).
//
// **This edits KiCad's own configuration**, which §5a originally refused to do —
// the generated `partmanager-*-lib-table` files were written for the user to
// copy from by hand. That was one manual step too many in practice: the names
// have to be transcribed per category, every new category is another round of
// it, and nothing on screen says which names to use. So the tables are merged
// instead, and the copy-by-hand files stay for anyone who wants them.
//
// Everything here is **pure text** — no filesystem, no Qt — so the merge rule can
// be tested against a real hand-written table without touching a KiCad install.
// Choosing *which* file to merge into, backing it up and writing it is the
// caller's job (`KicadController`), the same split as `StepConverter`.
//
// The merge is conservative by design, because the file being edited is one the
// user's other libraries live in:
//
//   - A row PartManager did not write is **carried across byte-identical**,
//     including its formatting, comments and any option KiCad has since added.
//   - A row is recognised as ours by its `(descr "Generated by PartManager")`,
//     not by its nickname — so a library the user added themselves and happened
//     to name `Resistors` is not silently taken over, it is replaced only if it
//     also carries our marker.
//   - Ours that no longer exist are dropped. A table pointing at a deleted
//     library makes KiCad complain on every launch.
//
// Idempotent: merging the same entries twice produces the same bytes.
// @see docs/design/ARCHITECTURE.md §5a
// @see PartManager_KicadLibraryGenerator.h, PartManager_KicadController.h
#pragma once

#include "PartManager_global.h"
#include <string>
#include <vector>

namespace PartManager
{

	// One row of a KiCad library table.
	struct PART_MANAGER_API KicadLibEntry
	{
		std::string name;   // the nickname KiCad shows
		std::string uri;    // "${PARTMANAGER_KICAD_LIBS}/symbols/Resistors.kicad_sym"
	};

	class PART_MANAGER_API KicadLibTable
	{
		KicadLibTable() = delete;
	public:
		// What marks a row as PartManager's, in the `descr` field KiCad round-trips untouched.
		static const char* const Marker;

		// The rows for a set of generated libraries.
		static std::vector<KicadLibEntry> symbolEntries(const std::vector<std::string>& libraryNames,
			const std::string& pathVariable);
		static std::vector<KicadLibEntry> footprintEntries(const std::vector<std::string>& libraryNames,
			const std::string& pathVariable);

		// `entries` merged into `existingText`. `rootTag` is "sym_lib_table" or "fp_lib_table";
		// it is what an empty or unreadable input is rebuilt as, so a missing table and a corrupt
		// one both end up as a valid table containing exactly our rows rather than as a failure
		// the user has to diagnose inside KiCad.
		static std::string merge(const std::string& existingText, const std::string& rootTag,
			const std::vector<KicadLibEntry>& entries);

		// True when the row on this line is one PartManager wrote.
		static bool isOurs(const std::string& line);
	};

}
