#include "kicad/PartManager_KicadLibTable.h"

#include <sstream>

namespace PartManager
{

	const char* const KicadLibTable::Marker = "Generated by PartManager";
	const char* const KicadLibTable::NicknamePrefix = "PartManager_";

	std::string KicadLibTable::nicknameFor(const std::string& libraryName)
	{
		const std::string prefix = NicknamePrefix;
		return libraryName.rfind(prefix, 0) == 0 ? libraryName : prefix + libraryName;
	}

	namespace
	{
		// ponytail: line-based, because KiCad writes exactly one `(lib ...)` per line and has
		// since v5. Ceiling: a table someone reformatted by hand so a row spans two lines is not
		// understood — the row is then carried across untouched, which is the safe direction.
		// Upgrade path is the s-expression reader in KicadGeometry.
		bool isLibRow(const std::string& line)
		{
			const size_t start = line.find_first_not_of(" \t");
			return start != std::string::npos && line.compare(start, 5, "(lib ") == 0;
		}

		std::string rowFor(const KicadLibEntry& entry)
		{
			return "  (lib (name \"" + entry.name + "\")(type \"KiCad\")(uri \"" + entry.uri
				+ "\")(options \"\")(descr \"" + KicadLibTable::Marker + "\"))";
		}

		std::vector<KicadLibEntry> entriesFor(const std::vector<std::string>& libraryNames,
			const std::string& pathVariable, const char* folder, const char* suffix)
		{
			std::vector<KicadLibEntry> entries;
			for (const std::string& name : libraryNames)
			{
				KicadLibEntry entry;
				// The nickname is prefixed, the path is not — the file on disk is still
				// symbols/Capacitors.kicad_sym.
				entry.name = KicadLibTable::nicknameFor(name);
				entry.uri = "${" + pathVariable + "}/" + folder + "/" + name + suffix;
				entries.push_back(entry);
			}
			return entries;
		}
	}

	std::vector<KicadLibEntry> KicadLibTable::symbolEntries(
		const std::vector<std::string>& libraryNames, const std::string& pathVariable)
	{
		return entriesFor(libraryNames, pathVariable, "symbols", ".kicad_sym");
	}

	std::vector<KicadLibEntry> KicadLibTable::footprintEntries(
		const std::vector<std::string>& libraryNames, const std::string& pathVariable)
	{
		return entriesFor(libraryNames, pathVariable, "footprints", ".pretty");
	}

	bool KicadLibTable::isOurs(const std::string& line)
	{
		return isLibRow(line) && line.find(Marker) != std::string::npos;
	}

	std::string KicadLibTable::merge(const std::string& existingText, const std::string& rootTag,
		const std::vector<KicadLibEntry>& entries)
	{
		std::string header = "(" + rootTag + "\n  (version 7)";
		std::vector<std::string> keptRows;

		// A file that does not open with the tag we were asked for is not this table — a wrong
		// path, or something that is not a lib table at all. Rebuilding is better than appending
		// our rows to the middle of an unrelated file.
		const bool readable = existingText.find("(" + rootTag) != std::string::npos;
		if (readable)
		{
			std::istringstream stream(existingText);
			std::string line;
			bool headerDone = false;
			std::string collectedHeader;
			while (std::getline(stream, line))
			{
				while (!line.empty() && (line.back() == '\r' || line.back() == '\n'))
				{
					line.pop_back();
				}
				if (isLibRow(line))
				{
					headerDone = true;
					if (!isOurs(line))
					{
						keptRows.push_back(line);   // someone else's library, byte for byte
					}
					continue;
				}
				// The closing paren of the table, and anything after it, is rebuilt rather than
				// kept — otherwise a second merge nests our rows outside the list.
				const size_t firstChar = line.find_first_not_of(" \t");
				if (firstChar != std::string::npos && line[firstChar] == ')')
				{
					continue;
				}
				if (!headerDone)
				{
					collectedHeader += (collectedHeader.empty() ? "" : "\n") + line;
				}
			}
			if (!collectedHeader.empty())
			{
				header = collectedHeader;   // keeps whatever (version N) the install already had
			}
		}

		std::string out = header + "\n";
		for (const std::string& row : keptRows)
		{
			out += row + "\n";
		}
		for (const KicadLibEntry& entry : entries)
		{
			out += rowFor(entry) + "\n";
		}
		return out + ")\n";
	}

}
