#include "kicad/PartManager_KicadLibraryGenerator.h"
#include "kicad/PartManager_KicadSymbolWriter.h"
#include "persistence/PartManager_PartRepository.h"
#include "persistence/PartManager_PartTypeRepository.h"
#include "persistence/PartManager_SellerRepository.h"
#include "PartManager_global.h"

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <map>
#include <sstream>
#include <system_error>

#if SQLITEWRAPPER_LIBRARY_AVAILABLE == 1
	#include "SQLite.h"
#endif

namespace PartManager
{

	const char* const KicadLibraryGenerator::PathVariable = "PARTMANAGER_KICAD_LIBS";

	namespace
	{
		std::string readFile(const std::filesystem::path& path)
		{
			std::ifstream in(path, std::ios::binary);
			if (!in)
			{
				return std::string();
			}
			std::ostringstream buffer;
			buffer << in.rdbuf();
			return buffer.str();
		}

		bool writeFile(const std::filesystem::path& path, const std::string& contents)
		{
			std::error_code error;
			std::filesystem::create_directories(path.parent_path(), error);
			std::ofstream out(path, std::ios::binary | std::ios::trunc);
			if (!out)
			{
				return false;
			}
			out << contents;
			return out.good();
		}
	}

	std::string KicadGenerationResult::summary() const
	{
		if (!ok)
		{
			return errorMessage;
		}
		std::string text = std::to_string(symbolsGenerated) + " symbol(s) in "
			+ std::to_string(librariesWritten) + " library file(s)";
		if (symbolsPreserved > 0)
		{
			// Named first among the caveats because it is the one the user has to act on.
			text += ", " + std::to_string(symbolsPreserved) + " left alone because they were "
				"edited in KiCad";
		}
		if (footprintsCopied > 0)
		{
			text += ", " + std::to_string(footprintsCopied) + " footprint(s)";
		}
		if (modelsCopied > 0)
		{
			text += ", " + std::to_string(modelsCopied) + " 3D model(s)";
		}
		if (!skippedForNoCategory.empty())
		{
			text += ", " + std::to_string(skippedForNoCategory.size())
				+ " part(s) skipped for having no KiCad category";
		}
		return text;
	}

	std::string KicadLibraryGenerator::libraryNameFor(const std::string& category)
	{
		std::string name;
		for (char c : category)
		{
			// KiCad's library nickname is used as `Nickname:Symbol`, so a colon would split it in
			// two, and a space makes the lib-table entry ambiguous.
			name += (c == ' ' || c == ':' || c == '/' || c == '\\') ? '_' : c;
		}
		return name.empty() ? std::string("PartManager") : name;
	}

	std::string KicadLibraryGenerator::symLibTable(const std::vector<std::string>& libraryNames,
		const std::string& pathVariable)
	{
		std::string out = "(sym_lib_table\n  (version 7)\n";
		for (const std::string& name : libraryNames)
		{
			out += "  (lib (name \"" + name + "\")(type \"KiCad\")(uri \"${" + pathVariable
				+ "}/symbols/" + name + ".kicad_sym\")(options \"\")(descr \"Generated by PartManager\"))\n";
		}
		out += ")\n";
		return out;
	}

	std::string KicadLibraryGenerator::fpLibTable(const std::vector<std::string>& libraryNames,
		const std::string& pathVariable)
	{
		std::string out = "(fp_lib_table\n  (version 7)\n";
		for (const std::string& name : libraryNames)
		{
			out += "  (lib (name \"" + name + "\")(type \"KiCad\")(uri \"${" + pathVariable
				+ "}/footprints/" + name + ".pretty\")(options \"\")(descr \"Generated by PartManager\"))\n";
		}
		out += ")\n";
		return out;
	}

#if SQLITEWRAPPER_LIBRARY_AVAILABLE == 1

	namespace
	{
		// One part, resolved into everything the symbol needs. Built here so the writer stays
		// database-free.
		KicadSymbolSpec specFor(SQLiteWrapper::SQLite& db, const Part& part,
			const std::string& typeName, const std::string& filestorePath,
			const std::filesystem::path& modelsDir, int& modelsCopied)
		{
			KicadSymbolSpec spec;
			spec.name = part.name;
			spec.baseSymbol = KicadSymbolWriter::baseSymbolForType(typeName);
			spec.reference = KicadSymbolWriter::referenceForBase(spec.baseSymbol);
			// The MPN is what belongs on a schematic; the part's own name is a fallback for a
			// hand-made part that has none.
			spec.value = part.mpn.empty() ? part.name : part.mpn;
			spec.description = part.description;
			spec.keywords = typeName;
			spec.partId = part.id;
			spec.mouserPartNumber = SellerRepository::mouserPartNumber(db, part.id);

			for (const PartFile& file : PartRepository::listFiles(db, part.id))
			{
				const PartFileRole role = partFileRoleFromString(file.role);
				const std::filesystem::path stored =
					std::filesystem::path(filestorePath) / file.relativePath;
				if (role == PartFileRole::Datasheet && spec.datasheet.empty())
				{
					// A path rather than a URL: the file is already local, and the URL it came
					// from is not stored on the file row.
					spec.datasheet = stored.string();
				}
				else if (role == PartFileRole::Kicad3DModel)
				{
					// Copied into kicad_libs/3dmodels/ under its original name so the path in the
					// symbol is readable, and referenced through the same env var the lib tables
					// use — an absolute filestore path would not survive moving the database.
					const std::string name = file.originalFilename.empty()
						? std::filesystem::path(file.relativePath).filename().string()
						: file.originalFilename;
					std::error_code error;
					std::filesystem::create_directories(modelsDir, error);
					std::filesystem::copy_file(stored, modelsDir / name,
						std::filesystem::copy_options::overwrite_existing, error);
					if (!error)
					{
						++modelsCopied;
					}
					spec.model3DPath = "${" + std::string(KicadLibraryGenerator::PathVariable)
						+ "}/3dmodels/" + name;
				}
			}
			return spec;
		}
	}

	KicadGenerationResult KicadLibraryGenerator::generate(SQLiteWrapper::SQLite& db,
		const std::string& kicadLibsPath, const std::string& filestorePath,
		const std::vector<std::string>& forcePaths)
	{
		KicadGenerationResult result;
		if (kicadLibsPath.empty())
		{
			result.errorMessage = "No KiCad library folder is configured.";
			return result;
		}

		KicadEditTracker::createSchema(db);

		const std::filesystem::path root(kicadLibsPath);
		const std::filesystem::path symbolsDir = root / "symbols";
		const std::filesystem::path footprintsDir = root / "footprints";
		const std::filesystem::path modelsDir = root / "3dmodels";

		// Category -> the symbol blocks that library will hold, in part order.
		std::map<std::string, std::vector<std::string>> symbolsByCategory;
		// Category -> the target paths generated into it, so a preserved symbol can be matched.
		std::map<std::string, std::vector<std::pair<std::string, int>>> targetsByCategory;

		for (const PartType& type : PartTypeRepository::listTypes(db))
		{
			if (!type.kicadRelevant)
			{
				continue;
			}
			// §2b: a type with no category of its own inherits its nearest ancestor's.
			const std::string category = PartTypeRepository::effectiveKicadCategory(db, type.id);

			for (const Part& part : PartRepository::listParts(db, type.id))
			{
				if (category.empty())
				{
					// Counted, not dropped: otherwise the part simply never appears in KiCad and
					// there is nothing to explain why.
					result.skippedForNoCategory.push_back(part.name);
					continue;
				}
				const std::string libraryName = libraryNameFor(category);
				const std::string symbolName = KicadSymbolWriter::sanitizeSymbolName(part.name);
				const std::string targetPath = libraryName + ".kicad_sym:" + symbolName;

				const KicadSymbolSpec spec = specFor(db, part, type.name, filestorePath, modelsDir,
					result.modelsCopied);
				symbolsByCategory[libraryName].push_back(KicadSymbolWriter::symbolBlock(spec));
				targetsByCategory[libraryName].push_back({ targetPath, part.id });

				// Footprints are per-file, so they are a straight hash check against the file.
				for (const PartFile& file : PartRepository::listFiles(db, part.id))
				{
					if (partFileRoleFromString(file.role) != PartFileRole::KicadFootprint)
					{
						continue;
					}
					const std::filesystem::path stored =
						std::filesystem::path(filestorePath) / file.relativePath;
					const std::filesystem::path target = footprintsDir
						/ (libraryName + ".pretty")
						/ (symbolName + ".kicad_mod");
					const std::string onDisk = readFile(target);
					const KicadItemState state = KicadEditTracker::stateOf(db, target.string(), onDisk);
					const bool forced = std::find(forcePaths.begin(), forcePaths.end(),
						target.string()) != forcePaths.end();
					if (state == KicadItemState::EditedExternally && !forced)
					{
						KicadSkippedItem skipped;
						skipped.partId = part.id;
						skipped.partName = part.name;
						skipped.targetPath = target.string();
						result.preserved.push_back(skipped);
						continue;
					}
					const std::string contents = readFile(stored);
					if (!contents.empty() && writeFile(target, contents))
					{
						KicadEditTracker::record(db, part.id, KicadItemType::Footprint,
							target.string(), contents);
						++result.footprintsCopied;
					}
				}
			}
		}

		for (const std::pair<const std::string, std::vector<std::string>>& entry : symbolsByCategory)
		{
			const std::string& libraryName = entry.first;
			const std::filesystem::path libraryPath = symbolsDir / (libraryName + ".kicad_sym");

			// The existing file's symbols, byte for byte, so a hand-edited one can be carried
			// across without being re-serialised (which would itself count as an edit next run).
			std::map<std::string, std::string> onDiskSymbols;
			for (const std::string& block : KicadSymbolWriter::splitSymbols(readFile(libraryPath)))
			{
				onDiskSymbols[KicadSymbolWriter::symbolNameOf(block)] = block;
			}

			std::vector<std::string> blocks;
			const std::vector<std::pair<std::string, int>>& targets = targetsByCategory[libraryName];
			for (size_t i = 0; i < entry.second.size(); ++i)
			{
				const std::string& targetPath = targets[i].first;
				const int partId = targets[i].second;
				const std::string symbolName = targetPath.substr(targetPath.find(':') + 1);
				const std::string existing = onDiskSymbols.count(symbolName) != 0
					? onDiskSymbols[symbolName] : std::string();

				const KicadItemState state = KicadEditTracker::stateOf(db, targetPath, existing);
				const bool forced = std::find(forcePaths.begin(), forcePaths.end(), targetPath)
					!= forcePaths.end();
				if (state == KicadItemState::EditedExternally && !forced)
				{
					// The user's version wins and goes back into the file unchanged. The baseline
					// is deliberately left alone, so it keeps being reported until they decide.
					blocks.push_back(existing);
					KicadSkippedItem skipped;
					skipped.partId = partId;
					skipped.partName = symbolName;
					skipped.targetPath = targetPath;
					result.preserved.push_back(skipped);
					++result.symbolsPreserved;
					continue;
				}

				blocks.push_back(entry.second[i]);
				KicadEditTracker::record(db, partId, KicadItemType::Symbol, targetPath,
					entry.second[i]);
				++result.symbolsGenerated;
			}

			if (!writeFile(libraryPath, KicadSymbolWriter::library(blocks)))
			{
				result.errorMessage = "Could not write " + libraryPath.string();
				return result;
			}
			++result.librariesWritten;
		}

		std::vector<std::string> libraryNames;
		for (const std::pair<const std::string, std::vector<std::string>>& entry : symbolsByCategory)
		{
			libraryNames.push_back(entry.first);
		}
		// Written every run, including when nothing generated: a table listing a library that no
		// longer exists makes KiCad complain on every launch.
		writeFile(root / "partmanager-sym-lib-table", symLibTable(libraryNames, PathVariable));
		writeFile(root / "partmanager-fp-lib-table", fpLibTable(libraryNames, PathVariable));

		result.ok = true;
		return result;
	}

#endif

}
