#include "kicad/PartManager_KicadLibraryGenerator.h"
#include "kicad/PartManager_KicadSymbolWriter.h"
#include "filestore/PartManager_FileStore.h"
#include "persistence/PartManager_PartRepository.h"
#include "persistence/PartManager_PartTypeRepository.h"
#include "persistence/PartManager_SellerRepository.h"
#include "PartManager_global.h"

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <map>
#include <sstream>
#include <system_error>

#if SQLITEWRAPPER_LIBRARY_AVAILABLE == 1
	#include "SQLite.h"
#endif

namespace PartManager
{

	const char* const KicadLibraryGenerator::PathVariable = "PARTMANAGER_KICAD_LIBS";

	namespace
	{
		std::string readFile(const std::filesystem::path& path)
		{
			std::ifstream in(path, std::ios::binary);
			if (!in)
			{
				return std::string();
			}
			std::ostringstream buffer;
			buffer << in.rdbuf();
			return buffer.str();
		}

		bool writeFile(const std::filesystem::path& path, const std::string& contents)
		{
			std::error_code error;
			std::filesystem::create_directories(path.parent_path(), error);
			std::ofstream out(path, std::ios::binary | std::ios::trunc);
			if (!out)
			{
				return false;
			}
			out << contents;
			return out.good();
		}
	}

	std::string KicadGenerationResult::summary() const
	{
		if (!ok)
		{
			return errorMessage;
		}
		std::string text = std::to_string(symbolsGenerated) + " symbol(s) in "
			+ std::to_string(librariesWritten) + " library file(s)";
		if (symbolsFromAttachment > 0)
		{
			text += " (" + std::to_string(symbolsFromAttachment) + " from the part's own KiCad file)";
		}
		if (symbolsPreserved > 0)
		{
			// Named first among the caveats because it is the one the user has to act on.
			text += ", " + std::to_string(symbolsPreserved) + " left alone because they were "
				"edited in KiCad";
		}
		if (symbolsSyncedBack + footprintsSyncedBack > 0)
		{
			text += ", " + std::to_string(symbolsSyncedBack + footprintsSyncedBack)
				+ " edit(s) written back into the parts";
		}
		if (footprintsCopied > 0)
		{
			text += ", " + std::to_string(footprintsCopied) + " footprint(s)";
		}
		if (modelsCopied > 0)
		{
			text += ", " + std::to_string(modelsCopied) + " 3D model(s)";
		}
		if (!skippedForNoCategory.empty())
		{
			text += ", " + std::to_string(skippedForNoCategory.size())
				+ " part(s) skipped for having no KiCad category";
		}
		return text;
	}

	std::string KicadLibraryGenerator::libraryNameFor(const std::string& category)
	{
		std::string name;
		for (char c : category)
		{
			// KiCad's library nickname is used as `Nickname:Symbol`, so a colon would split it in
			// two, and a space makes the lib-table entry ambiguous.
			name += (c == ' ' || c == ':' || c == '/' || c == '\\') ? '_' : c;
		}
		return name.empty() ? std::string("PartManager") : name;
	}

	std::string KicadLibraryGenerator::symLibTable(const std::vector<std::string>& libraryNames,
		const std::string& pathVariable)
	{
		std::string out = "(sym_lib_table\n  (version 7)\n";
		for (const std::string& name : libraryNames)
		{
			out += "  (lib (name \"" + name + "\")(type \"KiCad\")(uri \"${" + pathVariable
				+ "}/symbols/" + name + ".kicad_sym\")(options \"\")(descr \"Generated by PartManager\"))\n";
		}
		out += ")\n";
		return out;
	}

	std::string KicadLibraryGenerator::fpLibTable(const std::vector<std::string>& libraryNames,
		const std::string& pathVariable)
	{
		std::string out = "(fp_lib_table\n  (version 7)\n";
		for (const std::string& name : libraryNames)
		{
			out += "  (lib (name \"" + name + "\")(type \"KiCad\")(uri \"${" + pathVariable
				+ "}/footprints/" + name + ".pretty\")(options \"\")(descr \"Generated by PartManager\"))\n";
		}
		out += ")\n";
		return out;
	}

#if SQLITEWRAPPER_LIBRARY_AVAILABLE == 1

	namespace
	{
		// One part, resolved into everything the symbol needs. Built here so the writer stays
		// database-free.
		KicadSymbolSpec specFor(SQLiteWrapper::SQLite& db, const Part& part,
			const std::string& typeName, const std::string& filestorePath,
			const std::filesystem::path& modelsDir, int& modelsCopied)
		{
			KicadSymbolSpec spec;
			spec.name = part.name;
			spec.baseSymbol = KicadSymbolWriter::baseSymbolForType(typeName);
			spec.reference = KicadSymbolWriter::referenceForBase(spec.baseSymbol);
			// The MPN is what belongs on a schematic; the part's own name is a fallback for a
			// hand-made part that has none.
			spec.value = part.mpn.empty() ? part.name : part.mpn;
			spec.description = part.description;
			spec.keywords = typeName;
			spec.partId = part.id;
			spec.mouserPartNumber = SellerRepository::mouserPartNumber(db, part.id);

			for (const PartFile& file : PartRepository::listFiles(db, part.id))
			{
				const PartFileRole role = partFileRoleFromString(file.role);
				const std::filesystem::path stored =
					std::filesystem::path(filestorePath) / file.relativePath;
				if (role == PartFileRole::Datasheet && spec.datasheet.empty())
				{
					// A path rather than a URL: the file is already local, and the URL it came
					// from is not stored on the file row.
					spec.datasheet = stored.string();
				}
				else if (role == PartFileRole::Kicad3DModel)
				{
					// Copied into kicad_libs/3dmodels/ under its original name so the path in the
					// symbol is readable, and referenced through the same env var the lib tables
					// use — an absolute filestore path would not survive moving the database.
					const std::string name = file.originalFilename.empty()
						? std::filesystem::path(file.relativePath).filename().string()
						: file.originalFilename;
					std::error_code error;
					std::filesystem::create_directories(modelsDir, error);
					std::filesystem::copy_file(stored, modelsDir / name,
						std::filesystem::copy_options::overwrite_existing, error);
					if (!error)
					{
						++modelsCopied;
					}
					spec.model3DPath = "${" + std::string(KicadLibraryGenerator::PathVariable)
						+ "}/3dmodels/" + name;
				}
			}
			return spec;
		}

		// Which of a library file's symbols is *the part's*.
		//
		// **Not simply the first.** A `.kicad_sym` PartManager wrote starts with the embedded
		// base symbols every generated symbol `(extends ...)`, so the first block is `PM_R` and
		// taking it would silently replace the part with a bare resistor outline. A vendor's
		// file, by contrast, holds exactly one symbol under its own name.
		//
		// So: the block named after the part if it is there, otherwise the first block that is
		// not one of the bases.
		std::string pickPartSymbol(const std::vector<std::string>& blocks,
			const std::string& symbolName)
		{
			std::vector<std::string> baseNames;
			for (const std::string& base : KicadSymbolWriter::baseSymbolBlocks())
			{
				baseNames.push_back(KicadSymbolWriter::symbolNameOf(base));
			}

			std::string firstNonBase;
			for (const std::string& block : blocks)
			{
				const std::string name = KicadSymbolWriter::symbolNameOf(block);
				if (name == symbolName)
				{
					return block;
				}
				if (firstNonBase.empty()
					&& std::find(baseNames.begin(), baseNames.end(), name) == baseNames.end())
				{
					firstNonBase = block;
				}
			}
			return firstNonBase;
		}

		// §5c: the symbol block for a part, taken from its attached `.kicad_sym` when it has one.
		// The attachment is a whole library file holding a single symbol, so it is split and the
		// first block taken; the block is then renamed to the part's symbol name and given
		// PartManager's own fields, so a vendor symbol keeps its real pins and graphics while
		// still resolving its footprint and pointing back at the part row.
		//
		// Empty when the part has no attachment or the file will not parse — the caller falls
		// back to the generated `(extends ...)` symbol rather than writing nothing.
		std::string symbolFromAttachment(SQLiteWrapper::SQLite& db, const Part& part,
			const std::string& filestorePath, const std::string& symbolName,
			const std::string& footprintRef, const KicadSymbolSpec& spec)
		{
			PartFile file;
			if (!FileStore::roleFile(db, part.id, PartFileRole::KicadSymbol, file))
			{
				return std::string();
			}
			const std::string text =
				readFile(std::filesystem::path(filestorePath) / file.relativePath);
			const std::string picked = pickPartSymbol(
				KicadSymbolWriter::splitSymbols(text), symbolName);
			if (picked.empty())
			{
				return std::string();
			}

			std::string block = KicadSymbolWriter::renamedSymbol(picked, symbolName);
			// The vendor writes a bare footprint name ("SOP65P640X110-16N"), which KiCad cannot
			// resolve without a library nickname in front of it.
			if (!footprintRef.empty())
			{
				block = KicadSymbolWriter::withProperty(block, "Footprint", footprintRef);
			}
			// The round trip back into this app, and the two fields the user actually looks for.
			block = KicadSymbolWriter::withProperty(block, "PM_PartID",
				spec.partId > 0 ? std::to_string(spec.partId) : std::string());
			if (!spec.mouserPartNumber.empty())
			{
				block = KicadSymbolWriter::withProperty(block, "Mouser P/N", spec.mouserPartNumber);
			}
			if (!spec.datasheet.empty())
			{
				block = KicadSymbolWriter::withProperty(block, "Datasheet", spec.datasheet);
			}
			if (!spec.model3DPath.empty())
			{
				block = KicadSymbolWriter::withProperty(block, "PM_3DModel", spec.model3DPath);
			}
			return block;
		}

		// §5c: writes `content` into the part's slot, but only when it differs from what is
		// already there — an unconditional write would make a new filestore row on every
		// regeneration and the "2 copies" would drift apart in metadata if not in bytes.
		// Returns true when something was actually written.
		bool syncAttachment(SQLiteWrapper::SQLite& db, FileStore& store, int partId,
			PartFileRole role, const std::string& content, const std::string& fileName)
		{
			if (content.empty())
			{
				return false;
			}
			PartFile existing;
			if (FileStore::roleFile(db, partId, role, existing)
				&& existing.contentHash == FileStore::hashBytes(content))
			{
				return false;   // already identical, which is the steady state
			}
			return store.replaceRoleFileBytes(db, partId, role, content, fileName) != 0;
		}
	}

	KicadGenerationResult KicadLibraryGenerator::generate(SQLiteWrapper::SQLite& db,
		const std::string& kicadLibsPath, const std::string& filestorePath,
		const std::vector<std::string>& forcePaths)
	{
		KicadGenerationResult result;
		if (kicadLibsPath.empty())
		{
			result.errorMessage = "No KiCad library folder is configured.";
			return result;
		}

		KicadEditTracker::createSchema(db);

		// §5c writes back into the part's attachments, so the generator needs the store the
		// editor uses — the same single-slot rule, from the same place.
		FileStore store(filestorePath);

		const std::filesystem::path root(kicadLibsPath);
		const std::filesystem::path symbolsDir = root / "symbols";
		const std::filesystem::path footprintsDir = root / "footprints";
		const std::filesystem::path modelsDir = root / "3dmodels";

		// Category -> the symbol blocks that library will hold, in part order.
		std::map<std::string, std::vector<std::string>> symbolsByCategory;
		// Category -> the target paths generated into it, so a preserved symbol can be matched.
		std::map<std::string, std::vector<std::pair<std::string, int>>> targetsByCategory;

		for (const PartType& type : PartTypeRepository::listTypes(db))
		{
			if (!type.kicadRelevant)
			{
				continue;
			}
			// §2b: a type with no category of its own inherits its nearest ancestor's.
			const std::string category = PartTypeRepository::effectiveKicadCategory(db, type.id);

			for (const Part& part : PartRepository::listParts(db, type.id))
			{
				if (category.empty())
				{
					// Counted, not dropped: otherwise the part simply never appears in KiCad and
					// there is nothing to explain why.
					result.skippedForNoCategory.push_back(part.name);
					continue;
				}
				const std::string libraryName = libraryNameFor(category);
				const std::string symbolName = KicadSymbolWriter::sanitizeSymbolName(part.name);
				const std::string targetPath = libraryName + ".kicad_sym:" + symbolName;

				KicadSymbolSpec spec = specFor(db, part, type.name, filestorePath, modelsDir,
					result.modelsCopied);
				// The footprint the symbol should reference, whether or not the part has one
				// attached — the .pretty entry is written under the symbol's name either way.
				PartFile footprintRow;
				const bool hasFootprint =
					FileStore::roleFile(db, part.id, PartFileRole::KicadFootprint, footprintRow);
				if (hasFootprint)
				{
					spec.footprint = libraryName + ":" + symbolName;
				}

				// §5c: the part's own `.kicad_sym` wins over the generic template.
				std::string block = symbolFromAttachment(db, part, filestorePath, symbolName,
					spec.footprint, spec);
				if (block.empty())
				{
					block = KicadSymbolWriter::symbolBlock(spec);
				}
				else
				{
					++result.symbolsFromAttachment;
				}
				symbolsByCategory[libraryName].push_back(block);
				targetsByCategory[libraryName].push_back({ targetPath, part.id });

				// Footprints are per-file, so they are a straight hash check against the file.
				if (hasFootprint)
				{
					const std::filesystem::path stored =
						std::filesystem::path(filestorePath) / footprintRow.relativePath;
					const std::filesystem::path target = footprintsDir
						/ (libraryName + ".pretty")
						/ (symbolName + ".kicad_mod");
					const std::string onDisk = readFile(target);
					const KicadItemState state = KicadEditTracker::stateOf(db, target.string(), onDisk);
					const bool forced = std::find(forcePaths.begin(), forcePaths.end(),
						target.string()) != forcePaths.end();
					if (state == KicadItemState::EditedExternally && !forced)
					{
						// §5c: the edit in KiCad wins and goes back into the part's attachment, so
						// the two copies agree again and the edit outlives `kicad_libs/`.
						if (syncAttachment(db, store, part.id, PartFileRole::KicadFootprint, onDisk,
							footprintRow.originalFilename.empty()
								? symbolName + ".kicad_mod" : footprintRow.originalFilename))
						{
							++result.footprintsSyncedBack;
							KicadEditTracker::rebaseline(db, target.string(), onDisk);
						}
						KicadSkippedItem skipped;
						skipped.partId = part.id;
						skipped.partName = part.name;
						skipped.targetPath = target.string();
						result.preserved.push_back(skipped);
						continue;
					}
					const std::string contents = readFile(stored);
					if (!contents.empty() && writeFile(target, contents))
					{
						KicadEditTracker::record(db, part.id, KicadItemType::Footprint,
							target.string(), contents);
						++result.footprintsCopied;
					}
				}
			}
		}

		for (const std::pair<const std::string, std::vector<std::string>>& entry : symbolsByCategory)
		{
			const std::string& libraryName = entry.first;
			const std::filesystem::path libraryPath = symbolsDir / (libraryName + ".kicad_sym");

			// The existing file's symbols, byte for byte, so a hand-edited one can be carried
			// across without being re-serialised (which would itself count as an edit next run).
			std::map<std::string, std::string> onDiskSymbols;
			for (const std::string& block : KicadSymbolWriter::splitSymbols(readFile(libraryPath)))
			{
				onDiskSymbols[KicadSymbolWriter::symbolNameOf(block)] = block;
			}

			std::vector<std::string> blocks;
			const std::vector<std::pair<std::string, int>>& targets = targetsByCategory[libraryName];
			for (size_t i = 0; i < entry.second.size(); ++i)
			{
				const std::string& targetPath = targets[i].first;
				const int partId = targets[i].second;
				const std::string symbolName = targetPath.substr(targetPath.find(':') + 1);
				const std::string existing = onDiskSymbols.count(symbolName) != 0
					? onDiskSymbols[symbolName] : std::string();

				const KicadItemState state = KicadEditTracker::stateOf(db, targetPath, existing);
				const bool forced = std::find(forcePaths.begin(), forcePaths.end(), targetPath)
					!= forcePaths.end();
				if (state == KicadItemState::EditedExternally && !forced)
				{
					// The user's version wins and goes back into the file unchanged...
					blocks.push_back(existing);
					// ...and into the part's own attachment, so the edit survives `kicad_libs/`
					// being deleted and the next run splices the edited symbol straight back in
					// (§5c). The attachment is stored as a whole one-symbol library, which is
					// exactly what symbolFromAttachment() reads and what KiCad opens directly.
					if (syncAttachment(db, store, partId, PartFileRole::KicadSymbol,
						KicadSymbolWriter::library({ existing }), symbolName + ".kicad_sym"))
					{
						++result.symbolsSyncedBack;
						// Re-baselined because the edit is now *ours* — it is what the attachment
						// holds, so the next run regenerates the same bytes and stops reporting it.
						KicadEditTracker::rebaseline(db, targetPath, existing);
					}
					KicadSkippedItem skipped;
					skipped.partId = partId;
					skipped.partName = symbolName;
					skipped.targetPath = targetPath;
					result.preserved.push_back(skipped);
					++result.symbolsPreserved;
					continue;
				}

				blocks.push_back(entry.second[i]);
				KicadEditTracker::record(db, partId, KicadItemType::Symbol, targetPath,
					entry.second[i]);
				++result.symbolsGenerated;
			}

			if (!writeFile(libraryPath, KicadSymbolWriter::library(blocks)))
			{
				result.errorMessage = "Could not write " + libraryPath.string();
				return result;
			}
			++result.librariesWritten;
		}

		std::vector<std::string> libraryNames;
		for (const std::pair<const std::string, std::vector<std::string>>& entry : symbolsByCategory)
		{
			libraryNames.push_back(entry.first);
		}
		// Written every run, including when nothing generated: a table listing a library that no
		// longer exists makes KiCad complain on every launch.
		writeFile(root / "partmanager-sym-lib-table", symLibTable(libraryNames, PathVariable));
		writeFile(root / "partmanager-fp-lib-table", fpLibTable(libraryNames, PathVariable));

		result.ok = true;
		return result;
	}

#endif

}
