#pragma once

#include "test.h"
#include "tests/TST_simple.h"
#include "tests/TST_DatabaseMetadata.h"
#include "tests/TST_SchemaMigrator.h"
#include "tests/TST_DatabaseCreate.h"
#include "tests/TST_PartTypeRepository.h"
#include "tests/TST_PartRepository.h"
#include "tests/TST_TagRepository.h"
#include "tests/TST_UnitTable.h"
#include "tests/TST_ValueParser.h"
#include "tests/TST_MainWindowController.h"
#include "tests/TST_PartEditorController.h"
#include "tests/TST_Settings.h"
#include "tests/TST_MouserSearchService.h"
//#include "test_nasted.h"